//! Generated protobuf code.
//!
//! This module contains code generated by tonic-build from the .proto files.
//! The actual files are generated during the build process.

// Include the generated code
// These files are generated by build.rs during compilation

/// Common types used across services.
pub mod common {
    include!(concat!(env!("OUT_DIR"), "/arcana.common.rs"));
}

/// User service definitions.
pub mod user {
    include!(concat!(env!("OUT_DIR"), "/arcana.user.rs"));
}

/// Authentication service definitions.
pub mod auth {
    include!(concat!(env!("OUT_DIR"), "/arcana.auth.rs"));
}

/// Health check service definitions.
pub mod health {
    include!(concat!(env!("OUT_DIR"), "/arcana.health.rs"));
}

/// Repository service definitions for layered deployment.
pub mod repository {
    include!(concat!(env!("OUT_DIR"), "/arcana.repository.rs"));
}

/// Job queue service definitions.
pub mod jobs {
    pub mod v1 {
        include!(concat!(env!("OUT_DIR"), "/arcana.jobs.v1.rs"));
    }
}
